### ISSUE TITLE
Make search available in more languages

### ISSUE THREAD

**Issue by aha999** [julianYaman/wikipedia-bot#19]
**Is your feature request related to a problem? Please describe.**
The topic search is apparently supported only in three languages.

**Describe the solution you'd like**
Make the bot recognize searches in other languages.

**Comment by aha999** [comment]
For example, personally i'm looking for Slovenian (or Slovene) support

**Comment by julianYaman** [comment]
Hello, I will work on it to implement Slovenian to the bot. 
More languages will be part of the bot soon with the next update!

**Comment by OnkelTem** [comment]
What about the 6th most popular language in the world? I speak about Russian.

**Comment by julianYaman** [comment]
@OnkelTem @aha999 Languages will be added now! If you have more suggestions, please write them down here or create a new issue. 

Thank you very much for helping me making the bot better 😃
